# Generated by Django 4.2.2 on 2023-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
