# Generated by Django 4.2.2 on 2023-07-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_patient_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
